#spring:
#  datasource:
#    url: 
#    username: root
#    password: 
#    driverClassName: com.mysql.cj.jdbc.Driver
#  jpa:
#    show-sql: true
#    hibernate:
#      dialect: org.hibernate.dialect.MySQL5Dialect
#      dll-auto: validate
#    properties:
#      hibernate:
#        format_sql: true
