spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/baza?serverTimezone=CET
    username: root
    password: 12345687
    driverClassName: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      dialect: org.hibernate.dialect.MySQL5Dialect
      dll-auto: validate
    properties:
      hibernate:
        format_sql: true
